# Generated by Django 3.2.25 on 2025-08-17 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('ph_no', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=10)),
                ('graduation_completed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3)),
                ('course', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='image/')),
            ],
        ),
    ]
